# Generated by Django 5.0 on 2024-03-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='contentimage',
        ),
    ]
