# Generated by Django 5.0 on 2024-02-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_faculty_department_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH')], default='B.TECH', max_length=50),
            preserve_default=False,
        ),
    ]
