# Generated by Django 5.0 on 2024-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE(R)', 'CSE(REGULAR)'), ('CSE(H)', 'CSE(HONORS)'), ('CSIT', 'CS&IT'), ('MECH', 'MECHANICAL'), ('civil', 'CIVIL'), ('ECE', 'ECE'), ('OTHERS', 'OTHERS')], max_length=50),
        ),
    ]
