# Generated by Django 5.0 on 2024-02-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
