# Generated by Django 5.0 on 2024-02-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_facultycoursemapping_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('ot', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'otp_table',
            },
        ),
        migrations.AlterField(
            model_name='facultycoursemapping',
            name='type',
            field=models.BooleanField(verbose_name='Faculty Type'),
        ),
    ]
