# Generated by Django 5.0 on 2024-02-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_otp_alter_facultycoursemapping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
